%{?!ros_distro:%global ros_distro lyrical}
%global pkg_name zenoh_bridge_dds
%global normalized_pkg_name %{lua:return (string.gsub(rpm.expand('%{pkg_name}'), '_', '-'))}

Name:           ros-lyrical-zenoh-bridge-dds
Version:        0.5.0
Release:        6%{?dist}
Summary:        ROS %{pkg_name} package

License:        EPL-2.0 and Apache-2.0
URL:            https://github.com/eclipse-zenoh/zenoh-plugin-dds
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  bloom-rpm-macros
BuildRequires:  cmake

%{?bloom_package}

%description
Bridge between ROS2/DDS and Eclipse zenoh (https://zenoh.io). It allows the
integration of zenoh applications with ROS2, or the tunneling of ROS2
communications between nodes via the zenoh protocol at Internet scale.


%package devel
Release:        %{release}%{?release_suffix}
Summary:        %{summary}
Provides:       %{name} = %{version}-%{release}
Provides:       %{name}%{?_isa} = %{version}-%{release}
Requires:       %{name}-runtime%{?_isa} = %{version}-%{release}

%description devel
Bridge between ROS2/DDS and Eclipse zenoh (https://zenoh.io). It allows the
integration of zenoh applications with ROS2, or the tunneling of ROS2
communications between nodes via the zenoh protocol at Internet scale.


%package runtime
Release:        %{release}
Summary:        %{summary}

%description runtime
Bridge between ROS2/DDS and Eclipse zenoh (https://zenoh.io). It allows the
integration of zenoh applications with ROS2, or the tunneling of ROS2
communications between nodes via the zenoh protocol at Internet scale.


%prep
%autosetup -p1


%generate_buildrequires
%bloom_buildrequires


%build
%cmake \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="%{bloom_prefix}" \
    -DAMENT_PREFIX_PATH="%{bloom_prefix}" \
    -DCMAKE_PREFIX_PATH="%{bloom_prefix}" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif

%cmake3_build


%install
%cmake_install


%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C %{__cmake_builddir} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
CTEST_OUTPUT_ON_FAILURE=1 \
    %cmake_build $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif


%files devel
%dir %{bloom_prefix}
%ghost %{bloom_prefix}/share/%{pkg_name}/package.xml


%files runtime
%{bloom_prefix}


%changelog
* Wed Apr 29 2026 ADLINK zenoh team <zenoh@adlink-labs.tech> - 0.5.0-6
- Autogenerated by Bloom

* Tue Apr 28 2026 ADLINK zenoh team <zenoh@adlink-labs.tech> - 0.5.0-5
- Autogenerated by Bloom

* Tue Apr 21 2026 ADLINK zenoh team <zenoh@adlink-labs.tech> - 0.5.0-4
- Autogenerated by Bloom
